### ISSUE TITLE
V2: Embedded structs are not inlined in the OpenAPI Spec

### ISSUE THREAD

**Issue by harry1453** [danielgtaylor/huma#113]
If I return the following type `B` as a body:

```go
type A struct {
    A string `json:"a"`
}

type B struct {
    A
    B string `json:"b"`
}
```

The response json will look like:
```json
{
  "a": "",
  "b": ""
}
```

Which is expected - this is how the `encoding/json` package works. However, the JSON Schema generated by Huma says that the response will be:
```json
{
  "A": {
    "a": ""
  },
  "b": ""
}
```

This is wrong - when generating the schema, Huma should inline embedded structs.

**Comment by danielgtaylor** [comment]
@harry1453 thanks for pointing this out BTW, my tests had missed this case and the API I ported to v2 as a proof-of-concept didn't use embedded structs so that's a miss on my part. It is fixed in `main` and I'll roll another beta release soon. Trying to get in as many fixes as I can, so if you see anything else broken please let me know!
