### ISSUE TITLE
Schema: anyOf, allOf, oneOf, not

### ISSUE THREAD

**Issue by nickajacks1** [danielgtaylor/huma#128]
The OpenAPI 3.1 inherits the definition of a Schema Object from JSON Schema Draft 2020-12, which defines [anyOf, allOf, oneOf, and not](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-10.2.1)

All things considered, extending Validate and the Schema struct to work with this doesn't seem hugely invasive (albeit nontrivial).
What I see being most tricky is having a single endpoint that can accept more than one of bool, int, float, string, []SomeStruct and SomeStruct (my own use case involves a POST endpoint accepting both []SomeStruct and SomeStruct). Perhaps it would be possible to do something along the lines of what sse.Register does with the eventTypeMap?

**Comment by danielgtaylor** [comment]
I've thought about this feature (variable input types) a lot over the past few months and am on the fence about whether to try supporting it in the base Huma library as a high-level feature. It complicates things quite a bit and I'm a fan of simple/straightforward APIs with one input type and one output type (which can be serialized in different formats, but the data type itself remains the same). Generally my opinion is that if things get too complicated I would rather provide the primitives and other people can write functionality on top of them, or since you provide your own router you can escape Huma altogether when needed.

@nickajacks1 see #131, which adds some support for these features under the hood and has an example for how you could use it to make an operation that supports `[]SomeStruct` or `SomeStruct` as input:

```go
// Step 1: create a custom schema
customSchema := &Schema{
	OneOf: []*Schema{
		{
			Type: TypeObject,
			Properties: map[string]*Schema{
				"foo": {Type: TypeString},
			},
		},
		{
			Type: TypeArray,
			Items: &Schema{
				Type: TypeObject,
				Properties: map[string]*Schema{
					"foo": {Type: TypeString},
				},
			},
		},
	},
}
customSchema.PrecomputeMessages()

Register(api, Operation{
	Method: http.MethodPut,
	Path:   "/one-of",
	// Step 2: register an operation with a custom schema
	RequestBody: &RequestBody{
		Required: true,
		Content: map[string]*MediaType{
			"application/json": {
				Schema: customSchema,
			},
		},
	},
}, func(ctx context.Context, input *struct {
	// Step 3: only take in raw bytes
	RawBody []byte
}) (*struct{}, error) {
	// Step 4: determine which it is and parse it into the right type.
	// We will check the first byte but there are other ways to do this.
	assert.EqualValues(t, '[', input.RawBody[0])
	var parsed []struct {
		Foo string `json:"foo"`
	}
	assert.NoError(t, json.Unmarshal(input.RawBody, &parsed))

	// ... do whatever you want with the input ...

	return nil, nil
})
```

That sort of functionality could be wrapped into a nice package with a better interface, like you alluded to regarding the `sse` package. What do you think? At least with this PR it makes it possible.
