### ISSUE TITLE
No way to access service from input struct Resolve function

### ISSUE THREAD

**Issue by marcind** [danielgtaylor/huma#13]
Since custom resolution is performed via a method on a struct, there's no good way to access service dependencies (for example when you need to validate by doing a look up in the service dependency)

**Comment by danielgtaylor** [comment]
Since you have access to the request in the resolvers you also have access to the request context. For now this is where you can put things which need to be accessed during resolution, e.g. a database connection by setting it in a middleware before the resolvers run.

In the future we can support a new `interface` which takes in additional stuff but we'll need to see how often this comes up as a problem.
