### ISSUE TITLE
Route grouping/sub routing

### ISSUE THREAD

**Issue by crossworth** [danielgtaylor/huma#182]
Hello, I'm trying to migrate a project from chi to Huma + chi (nice work btw) and one problem that I'm finding is relative to using chi route grouping/sub routing.

I have something like this:

 ```go
 router.Group(func(r chi.Router) {
	r.Use(CustomMiddleware())
	RegisterHandler(r, http.MethodGet, "/public-route", a.PublicRouteHandler)
	// how handle the case below
	r.Route("/api", func(r chi.Router) {
		r.Use(AuthenticatedMiddleware())
		RegisterHandler(r, http.MethodPost, "/private-route-1", a.PrivateRoute1Handler)
		r.Route("/sub-router-1", func(r chi.Router) {
			RegisterHandler(r, http.MethodGet, "/private-sub-route-1", a.PrivateSubRoute1Handler)
		})
		r.Route("/sub-router-2", func(r chi.Router) {
			RegisterHandler(r, http.MethodGet, "/private-sub-route-2", a.PrivateSubRoute2Handler)
		})
	})
})
```
Now, the `r.Use(CustomMiddleware())` is easy enough, I can just use `humachi.New` passing the returned `r chi.Router` after applying the middleware), registering the public route should be easy as well, now I'm not sure about the the first sub routing that adds the `AuthenticatedMiddleware`.

I dont really care about having to register the route as `/api/sub-router-1` (instead of using a `Route` + `/sub-router-1`), but I'm not sure how apply this middleware only for a few routes.

I could adapt the middleware and wrap the handler with it (`withAuthentication(a.PrivateRoute1Handler)`), but maybe there is a easy/better way and I'm not seeing it.

**Comment by crossworth** [comment]
@danielgtaylor thank you for the fast reply.

I was thinking in doing something like this:

```go
r.Group(func(r chi.Router) {
	r.Use(AuthenticatedMiddleware())
	localAPI := api.WithAdapter(humachi.NewAdapter(r))
	huma.Register(localAPI, huma.Operation{
		OperationID: "private-route-1",
		Method:      http.MethodGet,
		Path:        "/api/private-route-1",
	}, func(ctx context.Context, input *struct{}) (*struct{}, error) {
		return nil, nil
	})
}
```

The idea was having a way to override the adapter (`WithAdapter`) and returning a new `huma.API` with it, the only change would be the adapter that would point to the new provided adapter. I'm not sure if this would work (maybe we would need to clear the Huma middlewares on the copy as well) or if this makes sense in the first place if not all the routers support sub routers.

With all that said, I really liked your idea, its very clean and I think for my use case it should work.

Thanks again for the fast reply and the great work on this project.

(I will close this issue, but feel free to open if you think there is a need for keep it open).

**Comment by FlorianLoch** [comment]
I would like to reopen this question as I would like to add another perspective on this.

My problem is that I need my service to A) provide an API (and that I would like to do with Huma) and B) to serve a web app with some single-page application friendly handling.

From this the demand arises to pass only a sub router to Huma, let's say for `/api/v1` while I am serving the webapp from `/app` or even `/`.

I would therefore prefer to not give the root router to Huma because then I would still need to add routes on this router, though logically Huma is managing it. 
That would mix things up and I would be worried things interfere due to lack of separation.

So is it possibly to not only "bring my own router" but also to "bring my own subrouter"? Typewise this is fine but a quick test resulted in broken OpenAPI documentation because it tried to load the `openapi.json` from `/` instead of `/api/v1`...

So am I just holding it wrong or isn't that designed to work?

**Comment by burgesQ** [comment]
> I would like to reopen this question as I would like to add another perspective on this.
> 
> My problem is that I need my service to A) provide an API (and that I would like to do with Huma) and B) to serve a web app with some single-page application friendly handling.
> 
> From this the demand arises to pass only a sub router to Huma, let's say for `/api/v1` while I am serving the webapp from `/app` or even `/`.
> 
> I would therefore prefer to not give the root router to Huma because then I would still need to add routes on this router, though logically Huma is managing it. That would mix things up and I would be worried things interfere due to lack of separation.
> 
> So is it possibly to not only "bring my own router" but also to "bring my own subrouter"? Typewise this is fine but a quick test resulted in broken OpenAPI documentation because it tried to load the `openapi.json` from `/` instead of `/api/v1`...
> 
> So am I just holding it wrong or isn't that designed to work?

I came to the same conclusion and opened https://github.com/danielgtaylor/huma/pull/305

**Comment by cardinalby** [comment]
I believe the best way is to use groups for sub-routes, middlewares, etc. on Huma level, not on underlying router level.

This way we can have correct auto-generated Operation IDs, Summaries and operation paths in docs.

Pls check out [my solution](https://github.com/cardinalby/hureg) that wraps Huma registration pipeline

**Comment by FlorianLoch** [comment]
> I believe the best way is to use groups for sub-routes, middlewares, etc. on Huma level, not on underlying router level.

Hm, technically the router level might be "below" Huma because Huma makes use of the router - but from an architectural point of view, I tend to see the router to be "above" Huma. 
Thinking of it as a tree I could have a subtree of my routes within Huma - while serving some static files in another subtree. 

Putting Huma at the top of the tree I don't really see how to put something non-resty (like a file server) below it?

**Comment by cardinalby** [comment]
> Thinking of it as a tree I could have a subtree of my routes within Huma - while serving some static files in another subtree.

It's ok, you can still do that

> Putting Huma at the top of the tree I don't really see how to put something non-resty (like a file server) below it?

Also, you can always use Huma's `StreamResponse` to serve the files

In your example, if I got it correctly, you want to have `/openapi` endpoint at the root level while have all other endpoint declared with Huma under `/api` prefix?

With my approach you would:

```go
chiRouter := ...
api := hureg.NewAPIGen(humachi.New(chiRouter, cfg))
api = api.WithBasePath("/api")
```

and then use `api` everywhere which will guarantee that all you endpoints are registered with "/api" prefix but at the same time Huma will be aware of their full path and will generate valid docs and generated operation ids and summaries
