### ISSUE TITLE
Response Body can not be recognised in other directory and package

### ISSUE THREAD

**Issue by qdongxu** [danielgtaylor/huma#189]
Versions:
1.  github.com/danielgtaylor/huma/v2 v2.1.0 
2.  go 1.21.0

The `my-app` in the tutorial works fine.

after expand `my-app`, adding code all in main.go ( the **`main`** package), the open API spec works as expected[demo code 1](https://github.com/qdongxu/huma-my-app/tree/workwell):

Response Example:
```json
{
  "$schema": "http://example.com",
  "code": 0,
  "data": {
    "Greeting": "string",
    "Name": "string"
  },
  "msg": "string"
}
```

but after moving the expanded code to other directory and  package ( the **`my-app/module/submodule`** package), the open API spec pages shows errors [demo code 2](https://github.com/qdongxu/huma-my-app/tree/main) :

The `Responses` Section shows

>  Body   application/json
> No schema defined
```
Resonse Example:

Example cannot be created for this schema
Error: Invalid reference token: Responsemy-app
```

This is the first time I use huma. Is it a bug or any convention I did not follow? thanks for a kindly clarification.

**Comment by danielgtaylor** [comment]
Fascinating! Using a struct from another package *does* work as expected, but the combination of generics + a struct in another package is an edge case I haven't run into before. Rather than returning just the name of the type, I get something like `Response[my-app/module/submodule.BizData]` from a `reflect.Type.Name()` which gets turned into an invalid JSON pointer reference, which is why you are getting the error. Sorry about that.

I will need to update the [DefaultSchemaNamer](https://github.com/danielgtaylor/huma/blob/main/registry.go#L22-L40) to take into account generics with types from other modules. For now to get unstuck you could try [passing a modified schema namer function](https://github.com/danielgtaylor/huma/blob/main/defaults.go#L69) until this is fixed in Huma.
