### ISSUE TITLE
[Proposal] Add a global index prefix  to Schema Ref to avoid  panic for duplicate registry name.

### ISSUE THREAD

**Issue by qdongxu** [danielgtaylor/huma#213]
Huma generates the schema ref of parameter  type  by removing  the package name. This is a balance for readability. But the register will [panic](https://github.com/danielgtaylor/huma/blob/85278c95c7c6c6b11b4d0b696db38481923a6512/registry.go#L87) if there's same type name in different package.  Though it's arguable to use identical API parameter names in different package,  it's not good that huma restricts beyond the go language spec. 

Propose to add a global index prefix in [DefaultSchemaNamer](https://github.com/danielgtaylor/huma/blob/85278c95c7c6c6b11b4d0b696db38481923a6512/registry.go#L32)

**Comment by danielgtaylor** [comment]
@qdongxu how would this global index prefix work? You can already write your own schema namer that uses package paths if desired. What would this proposed feature give you and look like?

**Comment by qdongxu** [comment]
A developer  have to debug in case a panic occurs during starting the app and then try to look for a solution. This is a surprise to the developer. I hope huma works out of the box.

Here's a preview PR #214 for the solution, instead of prefix, I added as suffix to remain  order of the schema refs. 
Here's a duplicate [example](https://github.com/qdongxu/huma-my-app/commit/c0a44b1c1eb23e2b8cba7bd7b89c09d17dfd12c4) to check the visual effect on the web.

This solution is backward comaptible, there's no any suffix number appended if there's no duplicates.

**Comment by danielgtaylor** [comment]
Sorry, I meant to review your other PR. My concern is that this was the behavior in Huma v1 and we ran into serious issues where the order or registration mattered, meaning if you ever did a service-internal refactor where code registered operations in a different order then the generated OpenAPI might swap `Model1` vs `Model2`, which in turn breaks the generated SDKs. It was quite a pain to ensure the correct order was preserved between all changes and releases.

For Huma v2 it was decided to outright disallow that as a safety feature, which is why you see it panic. Unfortunately the check can only be done at runtime rather than compile time, but there's a good chance it can be caught during unit or integration testing.

I'm happy to review & merge the updated error message PR, but am hesitant about adding sequence numbers for the reasons above. You can of course provide your own schema naming function which generates sequence numbers, I'm just worried about making it the default behavior. Another option to bypass this problem entirely is to define a new type, for example:

```go
import (
  "example.com/pkg/a"
  "example.com/pkg/b"
)

type AItem a.Item
type BItem b.Item

// Later, when registering
huma.Register(api, ..., func(ctx context.Context, input *struct{
  Item AItem `json:"item"`
}) (...) {
  // Handler code...
}
```

That works fine with generics too.

**Comment by qdongxu** [comment]
I want to  follow some sort of best practice of the domain.  I prefer to avoid defining a special namer unless the naming rule in the road map of huma.

However, the type alias on the huma tier  is a lightweight compromising but acceptable solution.  I will leverage in this way. Thanks,  @danielgtaylor.
