### ISSUE TITLE
Best practices for managing cookies

### ISSUE THREAD

**Issue by furious-luke** [danielgtaylor/huma#227]
Hi there, thanks for such an amazing open source project. I've only just discovered Huma and am loving using it so far!

I'm wondering what the best practice is for accessing and setting cookies on requests and responses respectively? My use-case is around managing authentication sessions; I'd like to be able to access a cooke in a Huma middleware, if possible, but I'm unable to find an obvious utility to do so.

I suspect it's possible to go directly to the cookie header using something like `ctx.Header("Cookie")` from the Huma context, but I was hoping there might be a more convenient mechanism similar to other frameworks?

Thanks!

ETA: I'd also be interested to hear about any strategies for setting cookies from within request handlers?

**Comment by x-user** [comment]
@danielgtaylor, maybe we make some helper functions or extend huma.Context interface for such cases?

**Comment by danielgtaylor** [comment]
@furious-luke @x-user I'll be honest I haven't used cookies much in web APIs (most of my experience is with API keys or OAuth2 JWTs sent on each request). I understand the appeal of cookies getting re-used from a web app where a user has already logged into the system and the cookie essentially stores the session information.

I need to dig into the different routers and how they all handle cookies, and then I think @x-user is right we may want to extend the `huma.Context` to support some basic cookie set/get (or provide some utility functions that take a context and return or set a cookie). I'm open to ideas here from people who know more about this stuff!

**Comment by x-user** [comment]
I am not an expert by any means but i recommend utility functions because if we extend context we get this disadvantages:
<ol>
<li>Code duplication (each adapter will have it's onw cookie handling)</li>
<li>Multiple way to implement cookie handling in adapter (router specific or based on existing context methods)</li>
<li>Differences in cookie handling (routers can handle cookie differently for example in fiber if we try to get value of non existing cookie will return empty string, but in standard http package http.Request will return ErrNoCookie)</li>
</ol>

**Comment by furious-luke** [comment]
> I need to dig into the different routers and how they all handle cookies, and then I think @x-user is right we may want to extend the huma.Context to support some basic cookie set/get (or provide some utility functions that take a context and return or set a cookie). I'm open to ideas here from people who know more about this stuff!

An issue that this approach might end up finding is that sometimes cookies need to be specified from within a route handler function, much the same way the status of the response can have a sensible default, but sometimes it just needs to be set from within the handler. To support this, I think most other web frameworks provide a `SetCookie` function that is passed into the handler via some kind of context (in Gin, for example, the `gin.Context` carries with it a `SetCookie` function), which of course won't work with Huma as no such context is available from within handlers.

A potential option that might cover this scenario in Huma's case is to be able to treat cookies like headers and specify that the source of an input field can be a cookie. For example...

```go
type MyInput {
    HeaderField string `header:"HeaderName"`
    CookieFIeld string `cookie:"CookieName"`
}

type MyOutput {
    Status int
    CookieField `cookie:"cookie_field"
}
```

While this works well for accessing cookies, it may prove difficult to allow cookies to be set on the response struct due to cookies having a suite of different options that can be set, such as expiry, and security headers (which are pretty important). Perhaps it's possible to specify response cookies as structs that carry with them the required flags?

**Comment by x-user** [comment]
Maybe we should consider passing `huma.Context` to handlers. It will be breaking change, but with utility functions it will provide consistent way for working with cookies in middleware and handlers.

**Comment by furious-luke** [comment]
> Maybe we should consider passing huma.Context to handlers. It will be breaking change, but with utility functions it will provide consistent way for working with cookies in middleware and handlers.

That's true, and it probably wouldn't have to be a breaking change; I suspect it may be possible to implement the `context.Context` interface on `HumaContext`, passing through everything to the internal context represented by `Context()`.

Having said that, it definitely feels like a kind of "conceptual" breaking change. Not having access to the Huma context from within a handler forces the use of the input and output structs as the mechanism to access information (which IMO is a pretty neat way of doing it). By providing the Huma context an escape hatch will be present to allow accessing data in other ways. I could see how this may be subverting the intended use of Huma.

**Comment by x-user** [comment]
> Having said that, it definitely feels like a kind of "conceptual" breaking change. Not having access to the Huma context from within a handler forces the use of the input and output structs as the mechanism to access information (which IMO is a pretty neat way of doing it). By providing the Huma context an escape hatch will be present to allow accessing data in other ways. I could see how this may be subverting the intended use of Huma.

Totally agree, I feel the same way about this

**Comment by spa5k** [comment]
I think as long as we provide a way to set/get a cookie with the same parameters/type/interface as the default HTTP one, it should be good enough - 
```go
c := &http.Cookie{
			Name:     "state",
			Value:    state.String(),
			Path:     "/",
			MaxAge:   int(time.Hour.Seconds()),
			Secure:   r.TLS != nil,
			HttpOnly: true,
		}
http.SetCookie(w, c)
		
```
```go
stateCookie, err := r.Cookie("state")
```

**Comment by danielgtaylor** [comment]
For anyone following this issue, here's a quick example of how to set a cookie in the response right now: https://go.dev/play/p/mOmh8TxeKC2.

I'm continuing to work on making it easier to read cookies and return multiple `Set-Cookie` headers if needed.

**Comment by x-user** [comment]
I think there three ways to allow multiple cookies (without passing `huma.Context` to controllers):

1. Separate struct like body with `name:"cookie_name"` tag for fields
2. Single field with slice of http.Cookie and `header:"Set-Cookie"` tag
3. Multiple fields of http.Cookie type with `header:"Set-Cookie"` tags

We can even combine last two and allow slices and single value multiple `Set-Cookie` headers

**Comment by danielgtaylor** [comment]
Here is what I am thinking for the design so far:

### Reading Cookies

Add support for a `cookie` field tag for the request input struct. If its type is `http.Cookie` then you get the parsed cookie, otherwise you get just the cookie value. The adapter interface and each router adapter will be updated to provide a `Cookies() []*http.Cookie` method similar to https://pkg.go.dev/net/http#Request.Cookies. Usage example:

```go
huma.Register(api, huma.Operation{
	OperationID: "demo",
	Method:      http.MethodGet,
	Path:        "/demo",
}, func(ctx context.Context, input *struct {
	Session string       `cookie:"session"`
	Full    *http.Cookie `cookie:"full"`
}) (*struct{}, error) {
	fmt.Println("You sent", input.Session)
	fmt.Println("The 'full' cookie expires", input.Full.Expires)
	return nil, nil
})
```

The one caveat here is that Fiber uses its own cookie struct, so we'll need to translate for that router specifically, but I think that's an acceptable compromise.

### Writing Cookies

I want to modify the header serialization rules as follows:

1. If the type to be serialized implements `String() string`, then use it rather than `fmt.Printf("%v", value)`. This prevents needing to call `.String()` on your type yourself.
2. If the type to be serialized is a slice, then iterate through each item and use `AddHeader` instead of `SetHeader`. This enables any header to be sent multiple times if needed/desired without impacting existing behavior.

With those two generic changes, it is now possible to easily support writing one or more cookies without any extra work from the user. Here's the simple case:

```go
type Output struct {
	SetCookie *http.Cookie `header:"Set-Cookie"`
}

huma.Register(api, huma.Operation{
	OperationID: "demo",
	Method:      http.MethodGet,
	Path:        "/demo",
}, func(ctx context.Context, input *struct {}) (*Output, error) {
	resp := &Output{}

	resp.SetCookie = &http.Cookie{
		Name:  "foo",
		Value: "bar",
	}
	
	return resp, nil
})
```

And the more complex case of multiple cookies:

```go
type Output struct {
	SetCookie []*http.Cookie `header:"Set-Cookie"`
}

huma.Register(api, huma.Operation{
	OperationID: "demo",
	Method:      http.MethodGet,
	Path:        "/demo",
}, func(ctx context.Context, input *struct {}) (*Output, error) {
	resp := &Output{}

	resp.SetCookie = []*http.Cookie{
		{
			Name: "first",
			Value: "one",
		},
		{
			Name: "second",
			Value: "two",
		},
	}

	return resp, nil
})
```

What do you think? @x-user I like your idea of multiple `Set-Cookie` header tags but it seems like we'll have to special-case that specific header to use `AddHeader` over `SetHeader` and I'd like to avoid that if possible.

**Comment by spa5k** [comment]
For cookies, I think they should have a separate mini struct like it's for body - 

```go
type Output struct {
	Cookie {
          SetCookie []*http.Cookie `header:"Set-Cookie"`
        }
}
```

Similarly, for headers, and input/output. More verbose, but better control. At least for output part.

**Comment by x-user** [comment]
> ### Writing Cookies
> 
> I want to modify the header serialization rules as follows:
> 
>     1. If the type to be serialized implements `String() string`, then use it rather than `fmt.Printf("%v", value)`. This prevents needing to call `.String()` on your type yourself.
> 
>     2. If the type to be serialized is a slice, then iterate through each item and use `AddHeader` instead of `SetHeader`. This enables any header to be sent multiple times if needed/desired without impacting existing behavior.

I this this is the best way to go, most universal and somewhat consistent with inputs. Only question remains what to do for middleware? I think helper methods that work with context will fit for this role.

**Comment by danielgtaylor** [comment]
@furious-luke, @x-user, @spa5k please take a look at #258 and let me know what you think.

@spa5k I didn't go with a special `Cookie` struct because I don't think this is necessary and the less special casing we can do the better in my opinion. I also think it's very common to set just a single session cookie rather than many cookies at once, meaning for most people it would just be extra boilerplate to write. On top of that OpenAPI 3.1 doesn't have a good way to document which cookies your operation might set on the response.
