### ISSUE TITLE
Overridden `huma.NewError` gets called with `status` of 0 at initialization

### ISSUE THREAD

**Issue by servernoj** [danielgtaylor/huma#236]
Hello,

When I override `huma.NewError`, it gets called during the "initialization phase" at least once per every registered operation with an empty `message` and the `status` of 0.

Link to an illustrative example: https://goplay.tools/snippet/VqJWVzbLXDI

I tried to move the overriding call but it doesn't change things. 

Thank you

**Comment by danielgtaylor** [comment]
@servernoj yes, this is because it needs to get a dummy error instance to determine what your custom error type is and generate a schema for it.

This could be improved to only make the call once. Right now it does it on every registered operation, but we could cache the result to prevent further calls.

**Comment by servernoj** [comment]
@danielgtaylor so, as long as I return my custom error struct at the beginning of the overridden implementation, it should be OK?
```go
huma.NewError = func(status int, message string, errs ...error) huma.StatusError {
	if status == 0 {
		// case for https://github.com/danielgtaylor/huma/issues/236
		return &ErrorResponse{}
	}
        // ...
}
```
