### ISSUE TITLE
how to use huma with fiber api

### ISSUE THREAD

**Issue by ingio** [danielgtaylor/huma#243]
As I'm new to go (and programming in general) I couldn't get the boilerplate example converted to use fibre instead of chi.
Is that something I can get help with?

**Comment by danielgtaylor** [comment]
@ingio here's a quick example runnable in your browser based on the [Huma tutorial code](https://huma.rocks/tutorial/your-first-api/#operation):

https://go.dev/play/p/z2bBwlp0FBD?v=gotip

Hope that helps! BTW, as someone new to Go, I recommend avoiding Fiber unless you **really** need it because it uses a non-standard HTTP library underneath that does some surprising things that may trip you up. See the warning at https://github.com/valyala/fasthttp?tab=readme-ov-file#fasthttp--. Good luck writing your new service!

**Comment by ingio** [comment]
Wow ok thanks for that, I wasnt aware of this.
I thought it would be safe to use.

Then in that case how can I add basic auth using the chi middleware?
I found a way with fibre using fibre middleware and worked fine.
Link to example https://docs.gofiber.io/api/middleware/basicauth/#examples

Reason for all this is I want to convert my azure functions that I created running powershell into pure api go server with CRUD etc.

**Comment by danielgtaylor** [comment]
@ingio if you want to use chi then it looks like there is a basic auth middleware here:

https://github.com/go-chi/chi/blob/master/middleware/basic_auth.go

You can use it something like this:

```go
import (
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

// ...

router := chi.NewMux()
router.Use(middleware.BasicAuth("your-realm", map[string]string{
  "user1": "pass1",
  "user2": "pass2",
  // ...
}))
```

That middleware has nothing chi-specific in it, so it should work for a lot of routers theoretically. Hope that helps!

**Comment by ingio** [comment]
This worked perfectly, now I can use this as my base.
Thanks so much for quick response.

Regards
Ingi
