### ISSUE TITLE
Chunked Encoding

### ISSUE THREAD

**Issue by Fishwaldo** [danielgtaylor/huma#266]
Hi,
I can't see it (after a quick glance) but it it possible to disable chunked encoding by specifying a content-length header? 

(i'm guessing it needs to be done in a transformation?)

**Comment by danielgtaylor** [comment]
@Fishwaldo great question! For efficiency, the [default formats](https://github.com/danielgtaylor/huma/blob/main/defaults.go#L20) encode as streams so we don't know the content length before writing the response to the wire.

As an alternative, you could return a `[]byte` body as described at https://huma.rocks/features/response-outputs/#body to bypass serialization which would also let you manually set the `Content-Length` header as part of the response, though this probably isn't ideal as you'll have to write your own serialization utility functions.

What's the use-case for needing this? Is it just for one specific call or do you always want this behavior?

**Comment by Fishwaldo** [comment]
I'm using Huma as the backend for some embedded devices (esp32 based) and after testing it appears any response > ~500 bytes gets converted into a chunked response by Golang?

Excluding any error response, most of the data is less than 1K so it's just a lot of added complexity on the device side to decode a chunked response. (We receive the data into a fixed length buffer on the esp devices to avoid frequent allocations, and not knowing the length up front just complicates things there if the response is too big as well)


Looking at the API there doesn't appear to be a way to wrap the encoder to return any headers either right?

**Comment by danielgtaylor** [comment]
@Fishwaldo unfortunately no you can't wrap the encoder to return additional headers (it sends the status code and headers before beginning the streaming to marshal the data anyway). It's not the most efficient thing in the world, but here's an example of how you can accomplish it with a plain router-specific middleware. I don't know what router you are using but this example uses Chi:

https://go.dev/play/p/XWV97665LgI

How it works:

1. Add a new middleware that runs on every request.
2. Create a `http.ResponseWriter` that captures the output, and use it to wrap the writer in the middleware.
3. Call the next middleware/handler, when they are all done, write the `Content-Type` header using the captured body size, then send the status code and body over the wire.
4. Do all this using a `sync.Pool` to amortize the cost of allocations during heavy traffic (it lets pre-allocated buffers be re-used between requests that happen near each other). With this the perf really isn't bad, especially since your responses tend to be small too.

I know it's not perfect but maybe this can work for your use case? If this isn't the only use-case for the API then maybe you can also have the middleware change behavior based on incoming `User-Agent` header or URL path.

**Comment by danielgtaylor** [comment]
@Fishwaldo let me know if that doesn't answer the question, and feel free to reopen!
