### ISSUE TITLE
Nested resolvers stopped working

### ISSUE THREAD

**Issue by servernoj** [danielgtaylor/huma#274]
Hello,

I had a nested resolver in the form shown below that used to work (I think before v2.5.0 release). When I tried it today (with v2.5.0), the inner-most resolver was not called. 

Example:

```go
type MyInput struct {
	Nested
	FieldA string
}

type Nested struct {
	FieldB string
}

func (input *Nested) Resolve(ctx huma.Context) (errs []error) {
	// not called
	return nil
}

func (input *MyInput) Resolve(ctx huma.Context) (errs []error) {
	// called as expected
	return nil
}
```

I suspect v2.5.0 because some changes were applied in https://github.com/danielgtaylor/huma/pull/235 in response to https://github.com/danielgtaylor/huma/issues/234 and that PR is listed under 2.5.0

I can refactor my resolvers, but I wanted to make sure that my understanding is correct. 

Thank you

**Comment by danielgtaylor** [comment]
@servernoj I suspect you're right this is by design due to how Go works with compile-time generated methods and the need in #235 to not call the same resolver twice. We have no way to detect whether they are the same resolver so have to stop processing the chain at the first one for embedded anonymous fields. This is how method overrides work traditionally so hopefully shouldn't be too surprising, sorry for the change in behavior though!

I think you can fix the behavior by explicitly calling the nested resolver if/when that behavior is desired:

```go
type MyInput struct {
	Nested
	FieldA string
}

type Nested struct {
	FieldB string
}

func (input *Nested) Resolve(ctx huma.Context) (errs []error) {
	return nil
}

func (input *MyInput) Resolve(ctx huma.Context) (errs []error) {
	if errs := input.Nested.Resolve(ctx); len(errs) > 0 {
		return errs
	}
	// do other work...
	return nil
}
```

I don't have time now but can confirm that hopefully works as expected later.

**Comment by servernoj** [comment]
@danielgtaylor, thank you for confirming, I went ahead and proceeded with exact same solution as you proposed, and I confirm it works :)
