### ISSUE TITLE
How to upload files and forms with huma?

### ISSUE THREAD

**Issue by ljg-cqu** [danielgtaylor/huma#28]

**Comment by danielgtaylor** [comment]
For non structured (not JSON/CBOR) input you can use an input byte stream, see https://github.com/danielgtaylor/huma#input-streaming. Example:

```go
app.Resource("/stream").Post("stream-example", "docs...",
	responses.Created(),
	responses.InternalServerError(),
).Run(func(ctx huma.Context, input struct {
	ContentType string `header:"Content-Type"`
	Body        io.Reader
}) {
	contents, err := ioutil.ReadAll(input.Body)
	if err != nil {
		ctx.WriteError(http.StatusInternalServerError, "Error reading input")
		return
	}

	fmt.Printf("Got %s input: %s\n", input.ContentType, string(contents))
	ctx.WriteHeader(http.StatusNoContent)
})
```

This can be called like:

```sh
# Curl example:
$ curl -XPOST :8888/stream -H 'Content-Type: my/custom-type' -d 'this is a test'

# Restish example:
$ echo 'this is a test' | restish post :8888/stream -H 'Content-Type: my/custom-type'
```

As for forms, [`http.Request.Form`](https://pkg.go.dev/net/http#Request) is not currently exposed, but you can access it via an [input resolver](https://github.com/danielgtaylor/huma#resolvers):

```go
type FormInput struct {
	Form url.Values
}

func (f *FormInput) Resolve(ctx huma.Context, r *http.Request) {
	f.Form = r.Form
}
```

Then use `FormInput` to [compose your input params](https://github.com/danielgtaylor/huma#input-composition) and you should be able to access `input.Form`.

**Comment by ljg-cqu** [comment]
Thank you for patient reply. I can now upload files from Postman with io.Reader, but it seams that is no button for file upload on Swagger UI.

**Comment by danielgtaylor** [comment]
Interesting, this isn't something I've had to handle before from the generates docs UI. It looks like it is possible to convince Swagger UI to show the button, e.g. see https://swagger.io/docs/specification/describing-request-body/file-upload/. Huma doesn't directly support setting that up via struct tags, but you can experiment with https://github.com/danielgtaylor/huma/#custom-openapi-fields to get it working.

I'm open to ideas how to make this easier within Huma itself since it looks like both Swagger UI and [RapiDoc](https://github.com/mrin9/RapiDoc/issues/45) seem to support the feature. What's the ideal way to make this work?
