### ISSUE TITLE
[Bug] Humago with custom docs does not work

### ISSUE THREAD

**Issue by mailbaoer** [danielgtaylor/huma#281]
When I use humago with custom docs followed by [#273](https://github.com/danielgtaylor/huma/issues/273#issuecomment-1973618623), but is raise  with `GET /docs matches the same requests as GET /docs`
![image](https://github.com/danielgtaylor/huma/assets/5282978/91e24685-b914-4595-9154-238fd79c08d6)

my sample code is [Here](https://go.dev/play/p/qrc5_N2SAe9)

**Comment by x-user** [comment]
I think it should be
```go
config := huma.DefaultConfig("My API", "1.0.0")
config.DocsPath = ""
// ..
api.Adapter().Handle(&huma.Operation{
	Method: http.MethodGet,
	Path:   "/docs",
}, func(ctx huma.Context) {
	// ..
}
// ..
```

**Comment by danielgtaylor** [comment]
@mailbaoer to provide a little more background, you want to set `config.DocsPath = ""` when using custom docs so that the API setup doesn't create the `/docs` route for you. Because it created it for you and then you re-registered it manually for the custom docs, that resulted in an error in your sample code saying it was registered twice.

**Comment by x-user** [comment]
@danielgtaylor, i think he made mistake because in your comment you made typo and use `config.DocsPath` as `Operation.Path` after setting it to empty string.

**Comment by danielgtaylor** [comment]
@x-user whoops, good catch. I updated the code example. Trying to juggle too many things 😂

**Comment by mailbaoer** [comment]
Great, worked!👍
