### ISSUE TITLE
How to access unmarshaled request body in middleware?

### ISSUE THREAD

**Issue by leonklingele** [danielgtaylor/huma#289]
Hi Daniel, thanks for creating Huma! I just started learning it today, so please excuse my unqualified questions :)

I have a request ID middleware which injects an `X-Request-ID` header to all responses: https://github.com/helsinki-systems/settleup/blob/c193e84673b94642136e81b917cd36f0109feef5/pkg/server/middlewares.go#L26

All request bodies ("inputs") embed a common struct which includes the request ID field: https://github.com/helsinki-systems/settleup/blob/c193e84673b94642136e81b917cd36f0109feef5/pkg/server/handlers.go#L12-L14 for example this one: https://github.com/helsinki-systems/settleup/blob/c193e84673b94642136e81b917cd36f0109feef5/pkg/server/handlers_members.go#L12-L14
This is so the request ID header is listed in the OpenAPI spec.

Is there a way to access this common struct in the request ID middleware so I don't have to retrieve it using `ctx.Header`? https://github.com/helsinki-systems/settleup/blob/c193e84673b94642136e81b917cd36f0109feef5/pkg/server/middlewares.go#L32

**Comment by danielgtaylor** [comment]
@leonklingele this isn't currently possible because they operate at different layers. The input struct doesn't exist yet when the middleware runs:

```mermaid
graph LR
  subgraph InputStructExists
    InputValidation
    Handler
  end

  Request ---> RouterMiddleware
  RouterMiddleware ---> HumaMiddleware
  HumaMiddleware ---> InputValidation
  InputValidation ---> Handler
  Handler ---> Response
```

So for now you need to read the header directly. If this becomes a more common ask we may need to investigate adding a request-side equivalent of the [response transformers](https://huma.rocks/features/response-transformers/).

Also, if you don't need the request ID in your handlers you could just document it without validation/parsing using `Parameters` in the `huma.Operation` struct:

```go
huma.Register(api, huma.Operation{
	OperationID: "get-demo",
	Summary:     "Get a demo",
	Method:      http.MethodGet,
	Path:        "/demo",
	Parameters: []*huma.Param{
		{Name: "X-Request-ID", In: "header", Description: "Unique Request ID"},
	},
}, func(ctx context.Context, input *struct{}) (*struct{}, error) {
	return nil, nil
})
```

Hopefully that helps! Let me know if you have any other questions.

**Comment by leonklingele** [comment]
Thanks! That clears it up for now!
