### ISSUE TITLE
Slice parameters? How to use?

### ISSUE THREAD

**Issue by bclements** [danielgtaylor/huma#325]
HI all,

I have an api I'm attempting to build.  Here are the structs for the input (request query params)

```
type getInput struct {
	Page     int `query:"page"`
	PageSize int `query:"size"`
	Sorts    []SortParam   `query:"sorted_by"`
	Filters  []FilterParam `query:"filters"`
}

type SortParam struct {
	Field string
	Order string
}

type FilterParam struct {
	Field    string      
	Operator string      
	Value    interface{} 
}
```

Calling my api using curl
curl --request GET   --url http://localhost:8888/test?filters=field1:eq:value1,field2:gt:value2 gives me the error

`{"$schema":"http://localhost:8888/schemas/ErrorModel.json","title":"Unprocessable Entity","status":422,"detail":"validation failed","errors":[{"message":"expected array","location":"query.filters"}]}`

I"ve tried a number of combinations to try to build an array/slice in my url.
'http://localhost:8888/test?filters=[{"field":"field1,"operator":"contains","value":"foo"}]'

'http://localhost:8888/test?filters=%5B{"field":"field1","operator":"contains","value":"foo"}%5D'

Nothing seems to work. Same error every time.

Neither of the slice related params filters nor sorted_by is working. The page and size int parameters are.

It's been a very long day so apologies if this is a user error.

Thanks for any help

**Comment by danielgtaylor** [comment]
@bclements good question. Arrays of objects for query params are not supported out of the box with Huma, and even the OpenAPI 3.1 spec [stops at arrays *xor* objects but not both together](https://spec.openapis.org/oas/v3.1.0#style-examples). That said, you can utilize the `encoding.TextUnmarshaler` interface along with `huma.SchemaProvider` to make this work with your first example request:

```go

type SortParam struct {
	Field string
	Order string
}

type SortParams struct {
	Items []SortParam
}

func (s *SortParams) UnmarshalText(text []byte) error {
	for _, item := range strings.Split(string(text), ",") {
		parts := strings.Split(item, ":")
		if len(parts) != 2 {
			return fmt.Errorf("invalid sort param: %s", item)
		}
		if parts[1] != "asc" && parts[1] != "desc" {
			return fmt.Errorf("invalid sort order: %s", parts[1])
		}
		s.Items = append(s.Items, SortParam{Field: parts[0], Order: parts[1]})
	}
	return nil
}

func (s *SortParams) Schema(registry huma.Registry) *huma.Schema {
	return &huma.Schema{
		Type: huma.TypeString,
	}
}
```

Here's a full runnable example with a success & error response: https://go.dev/play/p/gRMMpCyV-rm. Feel free to modify it if you want the user to pass JSON or other formats instead. This is how the documentation winds up looking:

<img width="793" alt="Screenshot 2024-03-19 at 08 48 38" src="https://github.com/danielgtaylor/huma/assets/106826/44141245-0eca-4f30-ae9f-a1643041c499">


Also, at least for the sorting scenario, I've seen other systems use a `[]string` where each item is the field name and a `-` prefix denotes descending, otherwise it's ascending. For example: `foo,-bar` would be equivalent to `foo:asc,bar:desc` in your format.

Given how many ways there are to pass complex structured data in query params I don't know which we should support (if any) in Huma's core, but I'm open to suggestions.

Also, before I forget, thank you so much @bclements for sponsoring the project! :tada: 🥳 🙌🏻

**Comment by danielgtaylor** [comment]
@bclements I'm going to close since I think this was answered. Feel free to re-open if needed! I shot you an email but it may have gotten lost, so no worries!
