### ISSUE TITLE
Dynamic Payload parsing in Huma

### ISSUE THREAD

**Issue by prnvbn** [danielgtaylor/huma#332]
Hi, I was wondering what the intended way is to dynamically parse request inputs in Huma?

For additional context, I want to consume GitHub webhooks that are sent as POST requests to my Huma server. I want to unmarshal these requests based on  a header sent in the request.

I can have something like the following but that means I have to unmarshal the body more than once! 

- Is there a way to dynamically marshal into a struct based on a header?

```go
type Payload struct {
	Event string `header:"X-GitHub-Event"`
	RawBody  []byte
}

// ProcessWebHook processes a GitHub webhook event
// This is the entrypoint for all GitHub webhook events
func (a App) ProcessWebHook(ctx context.Context, payload *Payload) (*struct{}, error) {
   ...
}
```

**Comment by danielgtaylor** [comment]
@prnvbn there is no built-in way to dynamically unmarshal into different structs based on the contents of some header. You could maybe repurpose https://github.com/danielgtaylor/huma/blob/main/examples/oneof-response/main.go for the input rather than output.

That said, given this is kind of a special case to handle Github events, keep in mind you still have access to your underlying router and can just handle this directly there, bypassing Huma for special case calls that don't really benefit much from Huma's functionality. Huma is supposed to complement your router, not replace it!

**Comment by prnvbn** [comment]
Hi, yepp that's what I thought :) Thank you. I will continue using RawBody

**Comment by danielgtaylor** [comment]
Closing as resolved, please re-open if that's not the case!

**Comment by betaprior** [comment]
I recently ran into this use case as well. Using `RawBody` and a resolver works well.
