### ISSUE TITLE
Panic in OnAddOperation

### ISSUE THREAD

**Issue by steeling** [danielgtaylor/huma#371]
`OnAddOperation` can panic [here](https://github.com/danielgtaylor/huma/blob/v2.12.0/transforms.go#L128) if one of the fields of a return type is an embedded struct (there might be a requirement that the embedded struct also has some methods on it)

Panics with

```
panic: reflect: embedded type with methods not implemented if type is not first field
```

**Comment by danielgtaylor** [comment]
@steeling here's a basic repro. This panics:

```go
type Foo struct {
	Field string `json:"field"`
}

func (f Foo) Method() string {
	return "bar"
}

// GreetingOutput represents the greeting operation response.
type GreetingOutput struct {
	Body struct {
		Foo
		Message string `json:"message" example:"Hello, world!" doc:"Greeting message"`
	}
}
```

This works (note the pointer method receiver):

```go
type Foo struct {
	Field string `json:"field"`
}

func (f *Foo) Method() string {
	return "bar"
}

// GreetingOutput represents the greeting operation response.
type GreetingOutput struct {
	Body struct {
		Foo
		Message string `json:"message" example:"Hello, world!" doc:"Greeting message"`
	}
}
```

Apparently this is a long-standing known issue in Go: https://github.com/golang/go/issues/15924. It's unclear right now if it can be worked around since it's a problem with the underlying language support for reflection.

In the meantime, you can use pointer method receivers or disable the transformer:

```go
config := huma.DefaultConfig("My API", "1.0.0")
config.CreateHooks = []func(Config) Config{}

// api := ... use config ...
```

**Comment by steeling** [comment]
I wonder if it's possible to catch the issue, and not render the schema link for specific objects  that suffer from this issue? Or is there an alterantive mechanism to construct the schema links?
