### ISSUE TITLE
Support Discriminator and DiscriminatorMap

### ISSUE THREAD

**Issue by chrisguitarguy** [danielgtaylor/huma#384]
There's already `OneOf` support and such, but speaking mostly of the _Discriminator_ section here: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

This would be a nice feature -- maybe doesn't need to be handled on the parsing side, but just on the schema side and let folks use `RawBody` or something to handle it.

I've handled this on the client side previously by Unmarshaling a struct with only the discriminator field, then determining the right target "real" struct and unmarshalling again. Probably not the most efficient.

```go
schema := huma.Schema{
  Discriminator: huma.Discriminator{
    PropertyName: "type",
    Mapping: map[string]*Schema{
     "oneType": *huma.Schema{ ... }
    }
  },
}
```

Could event add a "base" type with the property field and use that with discriminator and do the unmarshaling perhaps:

```go
type Base struct {
  Type string `json:"type"`
}

type SpecificType1 struct {
  Base
}

type SpecificType1 struct {
  Base
}

schema := huma.Schema{
  Discriminator: huma.Discriminator{
    PropertyName: "type",
    Base: reflect.TypeOf(...), // ??? not sure what would be appropriate here
    Mapping: map[string]*Schema{
     "oneType": *huma.Schema{ ... }
    }
  },
}
```

Or maybe a `schema.WithDiscriminator(...)` or similar func that would set `OneOf` to the values in the `Mapping`

Sorry if I missed some context around this one, I tried to search around issues and the code but didn't see anything related to discriminator, only `OneOf`.

Also happy to try and implement this if y'all think it's worthwhile.

**Comment by danielgtaylor** [comment]
@chrisguitarguy thanks for opening this issue. We don't currently have any special support for discriminator fields. Like you said, `oneOf` is supported in `huma.Schema` but is currently never generated from Go structs because Go doesn't have union types and you can't list implementations of an interface via reflection, plus there's a desire to generally keep things simple (i.e. Huma doesn't have to support *all* features of OpenAPI since OpenAPI is meant to describe *all* possible APIs).

That said, I'm not opposed to adding support for discriminators to `huma.Schema` for people who want to manually set them up, and like you said it may be possible to build some utilities on top of that (probably outside of the schema, maybe in a separate package?). I'm happy to review proposals and implementations with examples of how this would be used.

Given the potential complexity I'm also curious why this functionality is desired and what some examples of usage might be. In other systems like protobuf you don't really model explicit discriminated unions, it's more like a message with optional fields to all the other message types (possibly with a one-of, but that's just sugar it doesn't change the wire protocol or field names/types). Just trying to understand more about the use-cases and possible alternative approaches.

**Comment by chrisguitarguy** [comment]
>  I'm also curious why this functionality is desired and what some examples of usage might be

I've got quite a few APIs in Python and PHP where the input looks like this:

```
{
  "type": "example",
  "dto": "on the backend is based onthe type"
}
```

Example in Swagger UI:
![Screenshot 2024-04-16 at 11 29 31 AM](https://github.com/danielgtaylor/huma/assets/1010392/56648139-611f-445f-a521-fae2228ee295)

IMO, this is somewhat nicer for clients as it makes a particular field required vs...

> In other systems like protobuf you don't really model explicit discriminated unions, it's more like a message with optional fields to all the other message types

Which would mean that all fields could be null or missing. That's an invalid request, but the OpenAPI spec doesn't really say that at least one is required.

I've also done stuff like this:

```
{
  "type": "example",
  "example_value": { ... }
}
```

Where the `type` makes an `{type}_value` or `{type}` field required. And it's fine, but, IMO the generated api spec doesn't do a great job of conveying which fields are required/not required, etc.

I was going to go down this route for now with my current project and just do a little more work in the handler. 

It seems like this:

> you can't list implementations of an interface via reflection

is the crux of the issue though. And using discriminator map could mean that a lot of sugar could be provided by Huma, but it'd still be pretty gnarly to support in request `Body` fields without full fledged support for union types in the go language itself.

Though maybe somethign like this could be done with generics now:

```go
type RequestInput[T TypeOne | TypeTwo | TypeThree] struct {
  Body T
}
```
