### ISSUE TITLE
Generating the openapi.json offline

### ISSUE THREAD

**Issue by ant1g** [danielgtaylor/huma#442]
Hello,

I was looking for a way to generate the `openapi.json` "offline" without having to start the server and hitting the `/openapi.json` endpoint...

Is that possible?

Thanks!

**Comment by danielgtaylor** [comment]
@ant1g yep it's totally possible:

- https://huma.rocks/tutorial/client-sdks/#add-an-openapi-command
- https://github.com/danielgtaylor/huma/blob/main/examples/spec-cmd/main.go#L70-L78

Just be careful if you connect to a DB or other dependencies requiring credentials that you do so on server startup so that the OpenAPI command doesn't require credentials to be run!

**Comment by ant1g** [comment]
Thanks a lot, I will have a look!
