### ISSUE TITLE
Update dependencies (and set up auto-dep bumps)

### ISSUE THREAD

**Issue by leonklingele** [danielgtaylor/huma#543]
Huma's dependencies are slightly out of date (in CI we're now getting vulnerability alerts for one of them, that's how I noticed).

Can you please bump them and maybe also set up some auto-bump job such as [Renovate](https://github.com/renovatebot/github-action) or [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions)?

Thank you! 😊

**Comment by danielgtaylor** [comment]
@leonklingele thanks, yeah I have dependabot set up but right now they can't auto-merge due to Huma supporting back to Go 1.20. Now that 1.23 is released I'm thinking of updating the minimum Go version to 1.21 (supporting the last two versions like Go itself does).

> slices: package slices is not in GOROOT (/home/dependabot/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.20.10.linux-amd64/src/slices)

<img width="928" alt="Screenshot 2024-08-17 at 11 01 37" src="https://github.com/user-attachments/assets/920d60f6-8ac5-45e0-9580-33e911393c33">

**Comment by danielgtaylor** [comment]
FYI, I've updated to Go 1.21 since 1.23 is out now and have merged the critical dependabot for the next release.
