### ISSUE TITLE
Invalid Use of $schema

### ISSUE THREAD

**Issue by Fishwaldo** [danielgtaylor/huma#59]
Hi,
I'm looking at fixing the issue with DisableSchemaProperty not working... but think I've found another potential issue.

the $schema property is intended to identify the dialect of json-schema used, and not the actual schema for the json file we are presenting:

Simple Explanation:
https://www.tutorialspoint.com/json/json_schema.htm

From the actual specs:
https://json-schema.org/understanding-json-schema/reference/schema.html

This is why when copy/pasting the examples presented in the /docs UI, it fails validation if it includes the $schema property.

**Comment by danielgtaylor** [comment]
VSCode and many other editors support the use of `$schema` to point at the schema representing that item in order to power code completion, suggestions, and in-line validation, see for example https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json.

If something is failing in the docs I believe that's a different bug and we should address that instead of fundamentally changing a useful feature.
