### ISSUE TITLE
`huma.API.OpenAPI()` called from the CLI is missing field nullability, does not match hosted `/openapi.yaml`

### ISSUE THREAD

**Issue by mzhu22** [danielgtaylor/huma#618]
Hi!

I followed the suggestion at https://huma.rocks/features/cli/#custom-commands to add a CLI command to print out the OpenAPI spec for my API, for consumption by downstream tools.

I've noticed a couple of things:
1. Nullability is not reflected in this output. "null" doesn't appear in the generated spec, so downstream tools assume all fields are non-nullable by default.
2. The outputted spec looks very different from the one accessible from a running server at /openapi.yaml (and reflected in /docs). In the hosted spec, in addition to types correctly being unions on `null` where appropriate, the ordering of items is different.

This leads me to believe that huma does not use `OpenAPI()` internally to generate the spec, or that the server needs to start up in order to process some metadata.

What's going on here? Is there a way to print out the spec used for the docs page?

**Comment by danielgtaylor** [comment]
@mzhu22 thanks for pointing this out. The docs you linked to are a bit out of date and I'll try to get them updated ASAP. Until then you can use the [`api.OpenAPI().YAML()`](https://pkg.go.dev/github.com/danielgtaylor/huma/v2#OpenAPI.YAML) method to generate YAML the way the server does. This was done so that you don't need to rely on any YAML marshaling library/dependency and gives Huma flexibility in how it marshals these structures (to enable stuff like nullability). FYI there is also a `DowngradeYAML()` method to get OpenAPI 3.0 instead of 3.1, if you need that.

**Comment by mzhu22** [comment]
Great, thanks for the help!
