### ISSUE TITLE
Handling Field Matching and Validation for application/x-www-form-urlencoded in Huma

### ISSUE THREAD

**Issue by learning-go123** [danielgtaylor/huma#642]
Refer to this: https://github.com/danielgtaylor/huma/issues/285
I wrote the following code

```go
var DefaultFormPostFormat = huma.Format{
	Marshal: nil,
	Unmarshal: func(data []byte, v any) error {
		params, err := url.ParseQuery(string(data))
		if err != nil {
			return err
		}
		if vPtr, ok := v.(*interface{}); ok {
			m := map[string]any{}
			for k := range params {
				m[snakeToCamel(k)] = params.Get(k)
			}
			*vPtr = m
			return nil
		}
		return mapForm(v, params)
	},
}

config.Formats["application/x-www-form-urlencoded"] = DefaultFormPostFormat
```

There is a problem here. If the fields of params are more than the fields of the structure in v, it will not pass the validation. Turning off validation will introduce additional validators. Is there some better way to make the code more unified?

**Comment by danielgtaylor** [comment]
@learning-go123 sorry I don't entirely understand the question. Do you have a runnable example or some input example vs. input struct where this fails and what you would prefer to see happen?

**Comment by learning-go123** [comment]
@danielgtaylor https://go.dev/play/p/58af3WgDFjg

**Comment by danielgtaylor** [comment]
@learning-go123 aaaaah now I understand. Thank you for the example! Here's how you can make it work: https://go.dev/play/p/7oVfLkGBmcJ. What I did was make sure the schema is generated with `additionalProperties: true` rather than the default of `false` for strict validation. See the docs here:

https://huma.rocks/features/request-validation/?h=additionalproperties#strict-vs-loose-field-validation

It's also possible to modify the schemas after generation, e.g. go through `api.OpenAPI().Components.Schemas` and set the `AdditionalProperties` field to `true` manually wherever you need to, or to provide your own custom schema for a particular operation. Hope this helps!

**Comment by learning-go123** [comment]
Sorry, it was my oversight in reading the documentation. Thank you for your patience in answering. Thanks!
